language: python
python:
- 3.6
install:
- pip install -r requirements-dev.txt
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: collijk
  password:
    secure: JAoa58Tf4GD1mloXt9YDs2cfnWcJj4SdAhrofFVU9MCmdBYOdxBX8Tt4s6xhdOpQ1RpMpdI0GCwtUtdE2kAk7eoWM1mkuD8LVzVlvtcp7AiJ2tyEN9uqg4roGI/Gcdddroc+whkypiUvaxQYuEHOKLDg7cUstUNt7TZ8V0aKp51wpmzpyUSy0ZS+VGOyTkeiwydAW4GDY2QAWJ6nW2DcipLe9t+XIcckkvAGCDuzcLvC22olYM5MUGOmqFjl4FcXTvHnhxgL+aXMgagNbvPol788+QwHzUvkU9OaOBVu4NntYPKjqaCav7wXNbrh6YEeURphnccrGZ0/ITQrPH672YNgpzPAIChYcNM3wR2Jn9lYqEFOgiKl1QCcbadJLLtfjFN3OWRkKl2sx+fdemLwpPXOI1DrsVZ6Jm0ESw7uHQnbhNL1CdvZ4N9C/CcmpOt90GW1S8gA8xJPdvbblPSbALPv/myyYFHB62LANfVkm6Yw69G8YV/5rIoWuOohfFPjTXk6WZblM2O0F6ghjuUvi/9kRThtK9uABKyy81mYH16JJiC1SwNWQD7V/WaqQCbtpuJatJWMgXHxR3AzlDAWFt7hgNSeE9intwc71ZiBKFol2tOVeH/DI/xgic2hTgStpVG1aaQbzg05pYnbUQj9AwbCzuDyRgzjuFPedNuXaWg=
  on:
    distributions: sdist bdist_wheel
    repo: ihmeuw/gbd_mapping
    tags: true
