language: python
python:
- 3.6
install:
- pip install pytest
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: vivarium
  password:
    secure: h3jq+3HCey4Gd0kXYfj84+aM7MwAaY6fKfTbLd1T4piVpACxUSMXyj3G6iMykcCjKFjnEcJFwbH9k/ckZq2tdxNXEE9AhVJ9SdXTfRNmBUq5qCFoDWzpQ7xqkz+HIBcjE6fzyVjpprrDgRX3FKZXjANFWkkB4O+n+QQubJHCHzyS2mya5nrEFPJwauva02hcd5MLrsu2kWB53f2rQZF3r1Jo+8xSnpGWW+xzD7BcwlXzlP9e7YvjUblfTWs3gpU02qHBXVfcW3Kc9Bo/wdnc3ZedQSbbYfRmoBvYWLfkXqtl97Cf53h2E+BcGJCqhuRmh5PePX+OIJPUgM7r5P4hgZxH1VJHmCSfeASApsGk4R4tTA3wIvwE/FDoUNRjFvddcan5Vdr/YWRG9g8pi9gEMEoe9h29exIhQERDDgc6tOXuI0SNYxLPqZZhkRKYWJ5bmHOrHoZHY5po3VwkijlfNYDROqEUg7AKCipawpQE9cYHLfpI3l7Yh6plFLKBCpmt3yVev2T6pq7ZcP8RBNTgj7H9a+EmLAwu80zncyd6/s5d2tKAh2jrHUX+LKp6ZbvDspOtoVwcNWyoWIrfBqHkHJyVj+tBLRl4YgonluMTATidMkvYr+Kbi6dGstmUj65Wt5m68HSsQG82NP+IuXcKx485Kmm8XVqqhEktR7ma/xI=
  on:
    distributions: sdist bdist_wheel
    repo: ihmeuw/gbd_mapping
    tags: true
